<?php

    /**
     * Implements hook_init()
     */
    function webauth_redirect_init() {
        
        // Get list of pages to be redirected
        $pages = variable_get('webauth_redirect_pages', "admin\r\nuser");
        $pages = str_replace("\r\n", "\n", trim($pages));
        $pageArray = explode("\n", $pages);  // $pageArray = array('admin', 'user');
        
        // if 1st argument is in $pageArray, and user is not logged in, redirect them
        if (user_is_anonymous() && in_array(arg(0), $pageArray)) {
            
            // Get the destination variable
            $destination = variable_get('webauth_redirect_destination', '/asuwebauth-login');
            
            // Create the URL query back to this page
            $url = (empty($_SERVER['HTTPS']) ? 'http://' : 'https://') . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
            $query = str_replace('%url', $url, variable_get('webauth_redirect_query', 'callapp=%url'));
            
            // Redirect the user
            drupal_goto($destination, $query);
            
        }
        
    }


    /**
     * Valid permissions for this module
     * @return array An array of valid permissions for this module
     */
    function webauth_redirect_perm() {
        
        return array('access webauth_redirect', 'administer webauth_redirect');
        
    }
    
    
    /**
     * Implementation of hook_admin()
     */
    function webauth_redirect_admin() {
        
        $form = array();
        
        $form['pages']['webauth_redirect_pages'] = array(
            '#type' => 'textarea',
            '#title' => t('Redirect these pages'),
            '#default_value' => variable_get('webauth_redirect_pages', "admin\r\nuser"),
            '#description' => t("Enter one page per lineto be redirected when user is not authenticated."),
            '#required' => TRUE,
        );
        
        $form['pages']['webauth_redirect_destination'] = array(
            '#type' => 'textfield',
            '#title' => t('Redirect to this page'),
            '#default_value' => variable_get('webauth_redirect_destination', '/asuwebauth-login'),
            '#description' => t('The URL to redirect to if users are not logged in.'),
            '#required' => TRUE,
        );
        
        $form['pages']['webauth_redirect_query'] = array(
            '#type' => 'textfield',
            '#title' => t('URL Query'),
            '#default_value' => variable_get('webauth_redirect_query', 'callapp=%url'),
            '#description' => t('The query to be appended to the URL.  %url will be replaced with the URL the user is trying to access.'),
        );
        
        return system_settings_form($form);
        
    }
    
        
    /**
     * Implementation of hook_menu()
     */
    function webauth_redirect_menu() {
        
        $items = array();
        
        $items['admin/settings/webauth_redirect'] = array(
            'title' => t('Webauth Redirect'),
            'description' => t('Settings for Webauth Redirect.'),
            'page callback' => 'drupal_get_form',
            'page arguments' => array('webauth_redirect_admin'),
            'access arguments' => array('access administration pages'),
            'type' => MENU_NORMAL_ITEM,
      );
      
      return $items;
      
    }
